# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnplsystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnplsystem
  template:
    metadata:
      labels:
        app: bnplsystem
    spec:
      containers:
        - name: bnpl
          image: louaykharouf/bnpl:bnpl-web
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: bnpl-svc.default.svc.cluster.local #10.108.244.86
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: bnpl
            - name: DB_USERNAME
              valueFrom: 
                       secretKeyRef: 
                             name: db-secret
                             key: username
            - name: DB_PASSWORD
              valueFrom: 
                       secretKeyRef: 
                             name: db-secret
                             key: password
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bnplysystem-service
spec:
  selector:
    app: bnplsystem
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001