# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnpl
  template:
    metadata:
      labels:
        app: bnpl
    spec:
      containers:
        - name: db
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: bnpl
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
# persistent-volume-claim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce  # Use ReadWriteMany if you need multiple readers/writers
  resources:
    requests:
      storage: 5Gi  # Adjust the storage size as needed

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bnpl-svc
spec:
  selector:
    app: bnpl
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer